# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_pilot_ds_project',
                'doc_host': 'https://SergioPereo.github.io',
                'git_url': 'https://github.com/SergioPereo/nbdev_pilot_ds_project',
                'lib_path': 'nbdev_pilot_ds_project'},
  'syms': {'nbdev_pilot_ds_project.core': {'nbdev_pilot_ds_project.core.foo': ('core.html#foo', 'nbdev_pilot_ds_project/core.py')}}}
