# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ListaDeSuper.ipynb.

# %% auto 0
__all__ = ['Articulo', 'ListaDeSupermercado']

# %% ../nbs/ListaDeSuper.ipynb 3
class Articulo:
    def __init__(self, nombre: str, #este es el nombre del articulo
                    cantidad: int, #esta es la cantidad del articulo
                    agregado: bool = False #esto indica si ya fue agregado 
     ) -> None:
        self.nombre = nombre
        self.cantidad = cantidad
        self.agregado = agregado

    def __str__(self) -> str:
        estado = 'Agregado' if self.agregado else 'No Agregado'
        return f"Articulo : {self.nombre} (Cantidad: {self.cantidad}) - {estado}"
    __repr__ = __str__

# %% ../nbs/ListaDeSuper.ipynb 4
class ListaDeSupermercado:
    def __init__(self) -> None:
        self.articulos = []

    def agregar_articulo(self, articulo: Articulo) -> None:
        self.articulos.append(articulo)

    def imprimir_articulos(self) -> None:
        for articulo in self.articulos:
            print(articulo)

    def imprimir_articulos_no_agregados(self) -> None:
        for articulo in self.articulos:
            if not articulo.agregado:
                print(articulo)

    

# %% ../nbs/ListaDeSuper.ipynb 8
import nbdev; nbdev.nbdev_export()
